// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot;

/**
 * The Constants class provides a convenient place for teams to hold robot-wide
 * numerical or boolean constants. This class should not be used for any other
 * purpose. All constants should be declared globally (i.e. public static). Do
 * not put anything functional in this class.
 *
 * <p>
 * It is
 *  advised to statically import this class (or one of its inner classes)
 * wherever the constants are needed, to reduce verbosity.
 */
public class Constants {
   /**
	 * Which PID slot to pull gains from. Starting 2018, you can choose from
	 * 0,1,2 or 3. Only the first two (0,1) are visible in web-based
	 * configuration.
	 */
	public static final int kSlotIdx = 0;

	/**
	 * Talon SRX/ Victor SPX will supported multiple (cascaded) PID loops. For
	 * now we just want the primary one.
	 */
	public static final int kPIDLoopIdx = 0;

	/**
	 * set to zero to skip waiting for confirmation, set to nonzero to wait and
	 * report to DS if action fails.
	 */
	public static final int kTimeoutMs = 30;

	public static final int kCAN_IntakeRoller = 5;
	public static final int kCAN_TurretAgitator = 6;
	public static final int kCAN_TurretIndexer = 7;
	public static final int kCAN_TurretSlave = 3;
	public static final int kCAN_TurretMaster = 12;
	public static final int kCAN_TurretSpin = 10;
	public static final int kCAN_DriveLeft1 = 15;
	public static final int kCAN_DriveLeft2 = 14;
	public static final int kCAN_DriveLeft3 = 13;
	public static final int kCAN_DriveRight1 = 0;
	public static final int kCAN_DriveRight2 = 1;
	public static final int kCAN_DriveRight3 = 2;
	public static final int kCAN_Pigeon = 0;
	public static final int kCAN_PCM = 0;
	public static final int kCAN_PDP = 0;

	public static final int kPSOL_Intake_Ext = 1;
	public static final int kPSOL_Intake_Ret = 0;
	public static final int kPSOL_DriveShift_High = 2;
	public static final int kPSOL_DriveShift_Low = 3;


}
