// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.subsystems;

import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.shuffleboard.Shuffleboard;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

import com.ctre.phoenix.motorcontrol.ControlMode;
import com.ctre.phoenix.motorcontrol.can.TalonFX;
import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

/**
 *
 */
public class FlyWheel extends SubsystemBase {

    private TalonFX motorFlyWheelMaster;
    private TalonFX motorFlyWheelSlave;
 

    /**
    *
    */
    public FlyWheel() {

        motorFlyWheelMaster = new WPI_TalonFX(12);
        motorFlyWheelMaster.configFactoryDefault();
        motorFlyWheelMaster.setInverted(true);

        motorFlyWheelSlave = new WPI_TalonFX(3);
        motorFlyWheelSlave.configFactoryDefault();
        motorFlyWheelSlave.follow(motorFlyWheelMaster);

         
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

    public void my_FlyWheelRun(double speed) {
        motorFlyWheelMaster.set(ControlMode.PercentOutput, speed); //(speed);
    }
}
