// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;


import com.ctre.phoenix.motorcontrol.can.WPI_TalonFX;
import com.ctre.phoenix.motorcontrol.can.WPI_VictorSPX;
import edu.wpi.first.wpilibj.SpeedControllerGroup;

    


/**
 *
 */
public class TurretShoot extends SubsystemBase {
    

    

    
private WPI_TalonFX motorLeftFalcon;
private WPI_TalonFX motorRightFlacon;
private SpeedControllerGroup flyWheel;
private WPI_VictorSPX motorAgitator;
private WPI_VictorSPX motorIndexer;

    
    
    /**
    *
    */
    public TurretShoot() {
        
motorLeftFalcon = new WPI_TalonFX(12);
 
 

motorRightFlacon = new WPI_TalonFX(3);
 
 

SpeedControllerGroup flyWheel = new SpeedControllerGroup(motorLeftFalcon, motorRightFlacon  );
 addChild("FlyWheel",flyWheel);
 

motorAgitator = new WPI_VictorSPX(5);
 
 

motorIndexer = new WPI_VictorSPX(7);
 
 


    
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

