// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.XboxController;
import edu.wpi.first.wpilibj2.command.CommandBase;

import frc.robot.subsystems.FlyWheel_Vel_PID;

/**
 *
 */
public class FlyWheel_Run extends CommandBase {

    private final FlyWheel_Vel_PID m_FlyWheel_Vel_PID;

    private final XboxController m_controller;

    public FlyWheel_Run(FlyWheel_Vel_PID subsystem, XboxController controller) {

        m_FlyWheel_Vel_PID = subsystem;
        addRequirements(m_FlyWheel_Vel_PID);

        m_controller = controller;
    }

    // Called when the command is initially scheduled.
    @Override
    public void initialize() {
    }

    // Called every time the scheduler runs while the command is scheduled.
    @Override
    public void execute() {
        double speed = m_controller.getRawAxis(3);
        m_FlyWheel_Vel_PID.my_FlyWheel_Vel_PIDPercentOutput(speed);

    }

    // Called once the command ends or is interrupted.
    @Override
    public void end(boolean interrupted) {
        m_FlyWheel_Vel_PID.my_FlyWheel_Vel_PIDPercentOutput(0.0);
    }

    // Returns true when the command should end.
    @Override
    public boolean isFinished() {
        return false;
    }

    @Override
    public boolean runsWhenDisabled() {

        return false;

    }
}
