// RobotBuilder Version: 3.1
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package frc.robot.commands;

import edu.wpi.first.wpilibj.trajectory.constraint.TrajectoryConstraint.MinMax;
import edu.wpi.first.wpilibj2.command.InstantCommand;

import frc.robot.subsystems.Intake;

/**
 *
 */
public class IntakeRetract extends InstantCommand {

    private final Intake m_intake;

    public IntakeRetract(Intake subsystem) {

        m_intake = subsystem;
        addRequirements(m_intake);

    }

    // Called once when this command runs
    @Override
    public void initialize() {
        m_intake.my_intakeRetract();
    }

    @Override
    public boolean runsWhenDisabled() {

        return false;

    }
}
